version: '3.8'

networks:
  moex_collector:
    driver: bridge

services:
  # --- Kafka Service ---
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    networks:
      - moex_collector
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
    volumes:
      - ./consumer.properties:/etc/kafka/consumer.properties
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - kafka_data:/var/lib/kafka/data

  moex-collector:
    image: vielen1991/moex-collector:v1
    container_name: moex-collector
    hostname: moex-collector
    networks:
      - moex_collector
    environment:
      KAFKA_BROKER: kafka:29092
      POLL_INTERVAL: 15s
    depends_on:
      - kafka

  # --- Cassandra Service ---
  cassandra:
    image: cassandra:5.0.6
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    networks:
      - moex_collector
    volumes:
      - cassandra_data:/var/lib/cassandra

  nifi:
    image: apache/nifi:1.28.1
    container_name: nifi
    hostname: nifi
    networks:
      - moex_collector
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTP_PORT: 8443
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: secret_admin_password
    depends_on:
      - cassandra
      - kafka

volumes:
  cassandra_data:
  kafka_data: