version: '3.8'

networks:
  moex_collector:
    driver: bridge

services:
  # --- Kafka Service ---
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    networks:
      - moex_collector
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
    volumes:
      - ./consumer.properties:/etc/kafka/consumer.properties
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - kafka_data:/var/lib/kafka/data

  # --- Cassandra Service ---
  cassandra:
    image: cassandra:5.0.6
    container_name: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    networks:
      - moex_collector
    volumes:
      - cassandra_data:/var/lib/cassandra

  nifi:
    image: apache/nifi:1.28.1
    container_name: nifi
    hostname: nifi
    networks:
      - moex_collector
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTP_PORT: 8443
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: secret_admin_password
    volumes:
      - nifi_data:/opt/nifi
    depends_on:
      - cassandra
      - kafka

  # --- Spark Master ---
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    hostname: spark-master
    user: root # Avoid permission issues with mounted volumes
    # Explicit command to start the Master class
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WEBUI_PORT=8080
    ports:
      - "8080:8080" # Web UI
      - "7077:7077" # RPC Port
    networks:
      - moex_collector
    volumes:
      - spark-apps:/opt/spark/apps # Mount your JARs here
      - ./spark-jars/config-1.4.1.jar:/opt/spark/jars/config-1.4.1.jar
      - ./spark-jars/java-driver-core-shaded-4.13.0.jar:/opt/spark/jars/java-driver-core-shaded-4.13.0.jar
      - ./spark-jars/java-driver-shaded-guava-25.1-jre-graal-sub-1.jar:/opt/spark/jars/java-driver-shaded-guava-25.1-jre-graal-sub-1.jar
      - ./spark-jars/native-protocol-1.5.0.jar:/opt/spark/jars/native-protocol-1.5.0.jar
      - ./spark-jars/reactive-streams-1.0.3.jar:/opt/spark/jars/reactive-streams-1.0.3.jar
      - ./spark-jars/spark-cassandra-connector-driver_2.12-3.5.0.jar:/opt/spark/jars/spark-cassandra-connector-driver_2.12-3.5.0.jar
      - ./spark-jars/spark-cassandra-connector_2.12-3.5.0.jar:/opt/spark/jars/spark-cassandra-connector_2.12-3.5.0.jar

  # --- Spark Worker ---
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    user: root
    depends_on:
      - spark-master
    # Explicit command to start the Worker class and connect to Master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
    ports:
      - "8081:8081" # Worker Web UI
    networks:
      - moex_collector
    volumes:
      - spark-apps:/opt/spark/apps
      - ./spark-jars/config-1.4.1.jar:/opt/spark/jars/config-1.4.1.jar
      - ./spark-jars/java-driver-core-shaded-4.13.0.jar:/opt/spark/jars/java-driver-core-shaded-4.13.0.jar
      - ./spark-jars/java-driver-shaded-guava-25.1-jre-graal-sub-1.jar:/opt/spark/jars/java-driver-shaded-guava-25.1-jre-graal-sub-1.jar
      - ./spark-jars/native-protocol-1.5.0.jar:/opt/spark/jars/native-protocol-1.5.0.jar
      - ./spark-jars/reactive-streams-1.0.3.jar:/opt/spark/jars/reactive-streams-1.0.3.jar
      - ./spark-jars/spark-cassandra-connector-driver_2.12-3.5.0.jar:/opt/spark/jars/spark-cassandra-connector-driver_2.12-3.5.0.jar
      - ./spark-jars/spark-cassandra-connector_2.12-3.5.0.jar:/opt/spark/jars/spark-cassandra-connector_2.12-3.5.0.jar

volumes:
  cassandra_data:
  kafka_data:
  nifi_data:
  spark-apps: